-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;
CREATE TABLE IF NOT EXISTS public.fruits_for_sale (
    fruit_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    fruit_name character varying NOT NULL,
    fruit_img character varying NOT NULL,
    fruit_price numeric NOT NULL,
    fruit_seller character varying NOT NULL,
    fruit_description character varying NOT NULL,
    account_fname character varying NOT NULL,
    account_lname character varying NOT NULL,
    CONSTRAINT fruit_pk PRIMARY KEY (fruit_id)
);
COMMENT ON TABLE public.fruits_for_sale IS 'Fruits table where we store all the fruits data that we are selling.';
CREATE TABLE IF NOT EXISTS public.accounts (
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_fname character varying NOT NULL,
    account_lname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type character varying NOT NULL DEFAULT 'Client',
    profile_picture character varying NULL,
    CONSTRAINT account_pk PRIMARY KEY (account_id)
);
COMMENT ON TABLE public.accounts IS 'A table to store all the users accounts, for the ones that will buy the fruits and the ones selling the fruits.';
CREATE TABLE IF NOT EXISTS public.orders (
    order_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_price numeric NOT NULL,
    account_fname character varying NOT NULL,
    account_lname character varying NOT NULL,
    fruit_name character varying NOT NULL,
    fruit_price numeric NOT NULL,
    CONSTRAINT order_pk PRIMARY KEY (order_id)
);
ALTER TABLE public.fruits_for_sale
ADD CONSTRAINT unique_fruit_name UNIQUE (fruit_name);
ALTER TABLE public.accounts
ADD CONSTRAINT unique_account_fname UNIQUE (account_fname);
ALTER TABLE public.accounts
ADD CONSTRAINT unique_account_lname UNIQUE (account_lname);
COMMENT ON TABLE public.orders IS 'A table for all the placed orders';
ALTER TABLE IF EXISTS public.fruits_for_sale
ADD CONSTRAINT account_fname FOREIGN KEY (account_fname) REFERENCES public.accounts (account_fname) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public.fruits_for_sale
ADD CONSTRAINT account_lname FOREIGN KEY (account_lname) REFERENCES public.accounts (account_lname) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public.orders
ADD CONSTRAINT account_fname FOREIGN KEY (account_fname) REFERENCES public.accounts (account_fname) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public.orders
ADD CONSTRAINT account_lname FOREIGN KEY (account_lname) REFERENCES public.accounts (account_lname) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public.orders
ADD CONSTRAINT fruit_name FOREIGN KEY (fruit_name) REFERENCES public.fruits_for_sale (fruit_name) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
END;